# Generated by Django 3.2.15 on 2026-01-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('session_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('register_time', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=20)),
                ('item', models.CharField(blank=True, max_length=100)),
                ('purchase_time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=50)),
                ('event_time', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('click_time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('battle_type', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('event_time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='EventQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('raw_data', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done')], max_length=20)),
                ('enqueue_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='EventErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('raw_data', models.TextField()),
                ('error_message', models.TextField()),
                ('error_time', models.DateTimeField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
    ]
