# Generated by Django 3.2.15 on 2026-02-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
