# Generated by Django 3.2.15 on 2026-01-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='analysis.tagcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_play_time', models.FloatField()),
                ('active_days', models.IntegerField()),
                ('login_count', models.IntegerField()),
                ('battle_count', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('total_consume', models.FloatField()),
                ('avg_order_value', models.FloatField()),
                ('behavior_vector', models.JSONField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClusterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('algorithm', models.CharField(max_length=50)),
                ('model_version', models.CharField(max_length=50)),
                ('score_vector', models.JSONField()),
                ('update_time', models.DateTimeField()),
                ('player_tag', models.CharField(blank=True, default='', max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.tagcategory')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.tag')),
            ],
            options={
                'unique_together': {('player_id', 'category')},
            },
        ),
    ]
