# Generated by Django 3.2.15 on 2026-01-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTaskSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
