# Generated by Django 3.2.15 on 2026-02-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_actionlog_created_at'),
        ('analysis', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFeatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_play_time', models.FloatField()),
                ('login_count', models.IntegerField()),
                ('battle_count', models.IntegerField()),
                ('win_count', models.IntegerField()),
                ('total_consume', models.FloatField()),
                ('purchase_count', models.IntegerField()),
                ('behavior_time', models.JSONField()),
                ('active_dates', models.JSONField()),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
    ]
