# Generated by Django 3.2.15 on 2026-02-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_playerfeaturehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclusterresult',
            name='cluster_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
