# Generated by Django 3.2.15 on 2026-02-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_actionlog_created_at'),
        ('analysis', '0005_playerclusterresult_cluster_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClusterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spender_score', models.FloatField()),
                ('skill_score', models.FloatField()),
                ('activity_score', models.FloatField()),
                ('gacha_score', models.FloatField()),
                ('spender_level', models.IntegerField()),
                ('skill_level', models.IntegerField()),
                ('activity_level', models.IntegerField()),
                ('gacha_level', models.IntegerField()),
                ('spender_tag', models.CharField(max_length=50)),
                ('skill_tag', models.CharField(max_length=50)),
                ('activity_tag', models.CharField(max_length=50)),
                ('gacha_tag', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playerbasic')),
            ],
            options={
                'db_table': 'player_cluster_profile',
            },
        ),
    ]
