# Generated by Django 3.2.15 on 2026-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_playerclusterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtaskswitch',
            name='interval_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='systemtaskswitch',
            name='last_run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemtaskswitch',
            name='task_name',
            field=models.CharField(max_length=50),
        ),
    ]
